name: canCer

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Mendownload Ngrok.
      run: |
        Invoke-WebRequest https://github.com/denaubs/cancer/raw/main/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/denaubs/cancer/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/denaubs/cancer/main/wallpaper.png -OutFile wallpaper.bmp
        Invoke-WebRequest https://raw.githubusercontent.com/denaubs/cancer/main/wallpaper.bat -OutFile wallpaper.bat
    - name: Extracting Ngrok file
      run: Expand-Archive ngrok.zip
    - name: Connectting to Ngrok Account.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Activating . . .
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.bmp D:\a\wallpaper.bmp
        copy wallpaper.bat D:\a\wallpaper.bat
    - name: Creating Tunnel . . .
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - name: Connect to canCer, ready to use.
      run: cmd /c start.bat
    - name: Success! You can close this tab.
      run: | 
        Invoke-WebRequest https://github.com/denaubs/cancer/raw/main/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
